import os

srcdir  = "."
blddir  = "build"
VERSION = "0.1.0"

def listdirs(folder):
  list = []
  for root, folders, files in os.walk(folder):
    for folder in folders:
      list.append(os.path.join(root, folder))
  
  return list

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")

def build(bld):
  obj = bld.new_task_gen("cxx")
  obj.cxxflags = ["-fPIC", "-Wall", "-DCLD_WINDOWS"]
  obj.target = "chromium"
  obj.includes = ['.'] + listdirs('base') + listdirs('encodings') + listdirs('languages')
  obj.source = """
                encodings/compact_lang_det/cldutil.cc
                encodings/compact_lang_det/cldutil_dbg_empty.cc
                encodings/compact_lang_det/compact_lang_det.cc
                encodings/compact_lang_det/compact_lang_det_impl.cc
                encodings/compact_lang_det/ext_lang_enc.cc
                encodings/compact_lang_det/getonescriptspan.cc
                encodings/compact_lang_det/letterscript_enum.cc
                encodings/compact_lang_det/tote.cc
                encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc
                encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc
                encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc
                encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc
                encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc
                encodings/compact_lang_det/win/cld_htmlutils_windows.cc
                encodings/compact_lang_det/win/cld_unilib_windows.cc
                encodings/compact_lang_det/win/cld_utf8statetable.cc
                encodings/compact_lang_det/win/cld_utf8utils_windows.cc
                encodings/internal/encodings.cc
                languages/internal/languages.cc"""