name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build && npm run build:wasm

      - name: Publish
        run: npm publish --access public